// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwdstoijiislmibsfdft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3ZHN0b2lqaWlzbG1pYnNmZGZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MjQyNTYsImV4cCI6MjA3NDIwMDI1Nn0.GFkUn6m5djMdwzcYLI-__saFhI_uc5vNCdDN-78RuR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});